### ISSUE TITLE
incompatible to python3.6

### ISSUE THREAD

**Issue by sibbi77** [Robpol86/libnl#28]
Installed using: `pip3 install --upgrade --user git+https://github.com/Robpol86/libnl`
Test with python 3.6.8 (on Ubuntu 18.04):
```
$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from libnl.nl import nl_recvmsgs_default, nl_send_auto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sebastian/.local/lib/python3.6/site-packages/libnl/nl.py", line 25, in <module>
    from libnl.handlers import (NL_CB_ACK, nl_cb_clone, NL_CB_CUSTOM, NL_CB_DUMP_INTR, NL_CB_FINISH, NL_CB_INVALID,
  File "/home/sebastian/.local/lib/python3.6/site-packages/libnl/handlers.py", line 18, in <module>
    from libnl.msg import nl_msg_dump, nl_nlmsg_flags2str, nl_nlmsgtype2str, nlmsg_hdr
  File "/home/sebastian/.local/lib/python3.6/site-packages/libnl/msg.py", line 19, in <module>
    import libnl.linux_private.netlink
  File "/home/sebastian/.local/lib/python3.6/site-packages/libnl/linux_private/netlink.py", line 11, in <module>
    from libnl.misc import (bytearray_ptr, c_int, c_uint, c_uint16, c_uint32, c_ushort, SIZEOF_INT, SIZEOF_U16, SIZEOF_U32,
  File "/home/sebastian/.local/lib/python3.6/site-packages/libnl/misc.py", line 54, in <module>
    c_int = _class_factory(ctypes.c_int)
  File "/home/sebastian/.local/lib/python3.6/site-packages/libnl/misc.py", line 16, in _class_factory
    class ClsPyPy(base):
TypeError: __class__ set to <class 'libnl.misc._class_factory.<locals>.ClsPyPy'> defining 'ClsPyPy' as <class 'libnl.misc._class_factory.<locals>.ClsPyPy'>
```
I'm no python pro, thus I cannot fix it myself.

**Comment by Robpol86** [comment]
Unfortunately I'm no longer maintaining this project. I'm no longer going to work on the project I'll be using this on and if I do resume it I would probably write it in Golang instead.

**Comment by sibbi77** [comment]
ok, thanks.
